version: 0.2

phases:
  install:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - export LAST_MONTH=${LAST_MONTH:-$(date -d "1 month ago" +%Y-%m)}
      - export MONTH=${MONTH:-$(date +%Y-%m)}
      - export FINDCEP_S3_STORAGE=${FINDCEP_S3_STORAGE:-"s3://findcep-data"}
  pre_build:
    commands:
      - echo ":: INIT FINDCEP GEOLOCATION CEP UPDATER ::"
      - python3 -m pip install -r requirements.txt
      - aws s3 cp ${FINDCEP_S3_STORAGE}/npz/GEOCEP-${LAST_MONTH}.npz GEOCEP.npz
      - [ $? -ne 0 ] && exit 1
      - aws s3 cp ${FINDCEP_S3_STORAGE}/geo/geolocation-${MONTH}.json.gz .
      - [ $? -ne 0 ] && exit 1
  build:
    commands:
      - echo ":: UPDATE FINDCEP API GEOLOCATION CEP ::"
      - python3 scripts/generate_geocep_npz.py geolocation-${MONTH}.json.gz
      - [ $? -ne 0 ] && exit 1
  build:
  post_build:
    commands:
      - echo ":: FINDCEP GEOLOCATION CEP FINISH ::"
      [ ! -s GEOCEP.npz ] && echo 1
      - aws s3 cp GEOCEP.npz s3://findcep-data/npz/GEOCEP-$MONTH.npz
      - [ $? -ne 0 ] && exit 1
      - mv GEOCEP.npz vendor/GEOCEP.npz
      - [ $? -ne 0 ] && exit 1
      - AWS_DEFAULT_REGION=sa-east-1 chalice deploy --stage prod  
      - [ $? -ne 0 ] && exit 1


# vim: set ft=yaml et ts=2 sw=2 :
